apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consume-s3-example.fullname" . }}
  labels:
    {{- include "consume-s3-example.labels" . | nindent 4 }}
data:
  s3_bucket_name: {{ .Values.s3.bucket_name }}