apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "consumer-s3-example.fullname" . }}"
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.s3.role_sts_arn }}
  labels:
    {{- include "consumer-s3-example.labels" . | nindent 4 }}
